export default [
  {
    login: "kazmiali",
    id: 39811688,
    node_id: "MDQ6VXNlcjM5ODExNjg4",
    avatar_url: "https://avatars.githubusercontent.com/u/39811688?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kazmiali",
    html_url: "https://github.com/kazmiali",
    followers_url: "https://api.github.com/users/kazmiali/followers",
    following_url:
      "https://api.github.com/users/kazmiali/following{/other_user}",
    gists_url: "https://api.github.com/users/kazmiali/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kazmiali/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kazmiali/subscriptions",
    organizations_url: "https://api.github.com/users/kazmiali/orgs",
    repos_url: "https://api.github.com/users/kazmiali/repos",
    events_url: "https://api.github.com/users/kazmiali/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/kazmiali/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "ThadeuCesario",
    id: 27692953,
    node_id: "MDQ6VXNlcjI3NjkyOTUz",
    avatar_url: "https://avatars.githubusercontent.com/u/27692953?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/ThadeuCesario",
    html_url: "https://github.com/ThadeuCesario",
    followers_url: "https://api.github.com/users/ThadeuCesario/followers",
    following_url:
      "https://api.github.com/users/ThadeuCesario/following{/other_user}",
    gists_url: "https://api.github.com/users/ThadeuCesario/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/ThadeuCesario/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/ThadeuCesario/subscriptions",
    organizations_url: "https://api.github.com/users/ThadeuCesario/orgs",
    repos_url: "https://api.github.com/users/ThadeuCesario/repos",
    events_url: "https://api.github.com/users/ThadeuCesario/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/ThadeuCesario/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "iamfaatima",
    id: 70031321,
    node_id: "MDQ6VXNlcjcwMDMxMzIx",
    avatar_url: "https://avatars.githubusercontent.com/u/70031321?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/iamfaatima",
    html_url: "https://github.com/iamfaatima",
    followers_url: "https://api.github.com/users/iamfaatima/followers",
    following_url:
      "https://api.github.com/users/iamfaatima/following{/other_user}",
    gists_url: "https://api.github.com/users/iamfaatima/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/iamfaatima/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/iamfaatima/subscriptions",
    organizations_url: "https://api.github.com/users/iamfaatima/orgs",
    repos_url: "https://api.github.com/users/iamfaatima/repos",
    events_url: "https://api.github.com/users/iamfaatima/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/iamfaatima/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Bsef19a506-Numan-Anees",
    id: 72232339,
    node_id: "MDQ6VXNlcjcyMjMyMzM5",
    avatar_url: "https://avatars.githubusercontent.com/u/72232339?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Bsef19a506-Numan-Anees",
    html_url: "https://github.com/Bsef19a506-Numan-Anees",
    followers_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/followers",
    following_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/following{/other_user}",
    gists_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/subscriptions",
    organizations_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/orgs",
    repos_url: "https://api.github.com/users/Bsef19a506-Numan-Anees/repos",
    events_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Bsef19a506-Numan-Anees/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "moElhaj",
    id: 22400576,
    node_id: "MDQ6VXNlcjIyNDAwNTc2",
    avatar_url: "https://avatars.githubusercontent.com/u/22400576?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/moElhaj",
    html_url: "https://github.com/moElhaj",
    followers_url: "https://api.github.com/users/moElhaj/followers",
    following_url:
      "https://api.github.com/users/moElhaj/following{/other_user}",
    gists_url: "https://api.github.com/users/moElhaj/gists{/gist_id}",
    starred_url: "https://api.github.com/users/moElhaj/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/moElhaj/subscriptions",
    organizations_url: "https://api.github.com/users/moElhaj/orgs",
    repos_url: "https://api.github.com/users/moElhaj/repos",
    events_url: "https://api.github.com/users/moElhaj/events{/privacy}",
    received_events_url: "https://api.github.com/users/moElhaj/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "kpy815",
    id: 69370971,
    node_id: "MDQ6VXNlcjY5MzcwOTcx",
    avatar_url: "https://avatars.githubusercontent.com/u/69370971?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kpy815",
    html_url: "https://github.com/kpy815",
    followers_url: "https://api.github.com/users/kpy815/followers",
    following_url: "https://api.github.com/users/kpy815/following{/other_user}",
    gists_url: "https://api.github.com/users/kpy815/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kpy815/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kpy815/subscriptions",
    organizations_url: "https://api.github.com/users/kpy815/orgs",
    repos_url: "https://api.github.com/users/kpy815/repos",
    events_url: "https://api.github.com/users/kpy815/events{/privacy}",
    received_events_url: "https://api.github.com/users/kpy815/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Muzamil-07",
    id: 66633369,
    node_id: "MDQ6VXNlcjY2NjMzMzY5",
    avatar_url: "https://avatars.githubusercontent.com/u/66633369?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Muzamil-07",
    html_url: "https://github.com/Muzamil-07",
    followers_url: "https://api.github.com/users/Muzamil-07/followers",
    following_url:
      "https://api.github.com/users/Muzamil-07/following{/other_user}",
    gists_url: "https://api.github.com/users/Muzamil-07/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Muzamil-07/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Muzamil-07/subscriptions",
    organizations_url: "https://api.github.com/users/Muzamil-07/orgs",
    repos_url: "https://api.github.com/users/Muzamil-07/repos",
    events_url: "https://api.github.com/users/Muzamil-07/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Muzamil-07/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "sshahid1505",
    id: 19369350,
    node_id: "MDQ6VXNlcjE5MzY5MzUw",
    avatar_url: "https://avatars.githubusercontent.com/u/19369350?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/sshahid1505",
    html_url: "https://github.com/sshahid1505",
    followers_url: "https://api.github.com/users/sshahid1505/followers",
    following_url:
      "https://api.github.com/users/sshahid1505/following{/other_user}",
    gists_url: "https://api.github.com/users/sshahid1505/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/sshahid1505/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/sshahid1505/subscriptions",
    organizations_url: "https://api.github.com/users/sshahid1505/orgs",
    repos_url: "https://api.github.com/users/sshahid1505/repos",
    events_url: "https://api.github.com/users/sshahid1505/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/sshahid1505/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BSEF19A525",
    id: 72210139,
    node_id: "MDQ6VXNlcjcyMjEwMTM5",
    avatar_url: "https://avatars.githubusercontent.com/u/72210139?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BSEF19A525",
    html_url: "https://github.com/BSEF19A525",
    followers_url: "https://api.github.com/users/BSEF19A525/followers",
    following_url:
      "https://api.github.com/users/BSEF19A525/following{/other_user}",
    gists_url: "https://api.github.com/users/BSEF19A525/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/BSEF19A525/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/BSEF19A525/subscriptions",
    organizations_url: "https://api.github.com/users/BSEF19A525/orgs",
    repos_url: "https://api.github.com/users/BSEF19A525/repos",
    events_url: "https://api.github.com/users/BSEF19A525/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BSEF19A525/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Muhammad-Atif-Aqeel",
    id: 83976198,
    node_id: "MDQ6VXNlcjgzOTc2MTk4",
    avatar_url: "https://avatars.githubusercontent.com/u/83976198?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Muhammad-Atif-Aqeel",
    html_url: "https://github.com/Muhammad-Atif-Aqeel",
    followers_url: "https://api.github.com/users/Muhammad-Atif-Aqeel/followers",
    following_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/following{/other_user}",
    gists_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/subscriptions",
    organizations_url: "https://api.github.com/users/Muhammad-Atif-Aqeel/orgs",
    repos_url: "https://api.github.com/users/Muhammad-Atif-Aqeel/repos",
    events_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Muhammad-Atif-Aqeel/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bsef19a517",
    id: 72209282,
    node_id: "MDQ6VXNlcjcyMjA5Mjgy",
    avatar_url: "https://avatars.githubusercontent.com/u/72209282?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bsef19a517",
    html_url: "https://github.com/bsef19a517",
    followers_url: "https://api.github.com/users/bsef19a517/followers",
    following_url:
      "https://api.github.com/users/bsef19a517/following{/other_user}",
    gists_url: "https://api.github.com/users/bsef19a517/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bsef19a517/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bsef19a517/subscriptions",
    organizations_url: "https://api.github.com/users/bsef19a517/orgs",
    repos_url: "https://api.github.com/users/bsef19a517/repos",
    events_url: "https://api.github.com/users/bsef19a517/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bsef19a517/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "WaseekSenju",
    id: 58625384,
    node_id: "MDQ6VXNlcjU4NjI1Mzg0",
    avatar_url: "https://avatars.githubusercontent.com/u/58625384?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/WaseekSenju",
    html_url: "https://github.com/WaseekSenju",
    followers_url: "https://api.github.com/users/WaseekSenju/followers",
    following_url:
      "https://api.github.com/users/WaseekSenju/following{/other_user}",
    gists_url: "https://api.github.com/users/WaseekSenju/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/WaseekSenju/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/WaseekSenju/subscriptions",
    organizations_url: "https://api.github.com/users/WaseekSenju/orgs",
    repos_url: "https://api.github.com/users/WaseekSenju/repos",
    events_url: "https://api.github.com/users/WaseekSenju/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/WaseekSenju/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Muhammad-Adrees",
    id: 81452417,
    node_id: "MDQ6VXNlcjgxNDUyNDE3",
    avatar_url: "https://avatars.githubusercontent.com/u/81452417?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Muhammad-Adrees",
    html_url: "https://github.com/Muhammad-Adrees",
    followers_url: "https://api.github.com/users/Muhammad-Adrees/followers",
    following_url:
      "https://api.github.com/users/Muhammad-Adrees/following{/other_user}",
    gists_url: "https://api.github.com/users/Muhammad-Adrees/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Muhammad-Adrees/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Muhammad-Adrees/subscriptions",
    organizations_url: "https://api.github.com/users/Muhammad-Adrees/orgs",
    repos_url: "https://api.github.com/users/Muhammad-Adrees/repos",
    events_url: "https://api.github.com/users/Muhammad-Adrees/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Muhammad-Adrees/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bsef19a523",
    id: 72210316,
    node_id: "MDQ6VXNlcjcyMjEwMzE2",
    avatar_url: "https://avatars.githubusercontent.com/u/72210316?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bsef19a523",
    html_url: "https://github.com/bsef19a523",
    followers_url: "https://api.github.com/users/bsef19a523/followers",
    following_url:
      "https://api.github.com/users/bsef19a523/following{/other_user}",
    gists_url: "https://api.github.com/users/bsef19a523/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bsef19a523/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bsef19a523/subscriptions",
    organizations_url: "https://api.github.com/users/bsef19a523/orgs",
    repos_url: "https://api.github.com/users/bsef19a523/repos",
    events_url: "https://api.github.com/users/bsef19a523/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bsef19a523/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "BSEF19A528",
    id: 72210054,
    node_id: "MDQ6VXNlcjcyMjEwMDU0",
    avatar_url: "https://avatars.githubusercontent.com/u/72210054?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/BSEF19A528",
    html_url: "https://github.com/BSEF19A528",
    followers_url: "https://api.github.com/users/BSEF19A528/followers",
    following_url:
      "https://api.github.com/users/BSEF19A528/following{/other_user}",
    gists_url: "https://api.github.com/users/BSEF19A528/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/BSEF19A528/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/BSEF19A528/subscriptions",
    organizations_url: "https://api.github.com/users/BSEF19A528/orgs",
    repos_url: "https://api.github.com/users/BSEF19A528/repos",
    events_url: "https://api.github.com/users/BSEF19A528/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/BSEF19A528/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Muhammad-Subhan-Ansari",
    id: 82394356,
    node_id: "MDQ6VXNlcjgyMzk0MzU2",
    avatar_url: "https://avatars.githubusercontent.com/u/82394356?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Muhammad-Subhan-Ansari",
    html_url: "https://github.com/Muhammad-Subhan-Ansari",
    followers_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/followers",
    following_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/following{/other_user}",
    gists_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/subscriptions",
    organizations_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/orgs",
    repos_url: "https://api.github.com/users/Muhammad-Subhan-Ansari/repos",
    events_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Muhammad-Subhan-Ansari/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "Shahouuudd",
    id: 83978301,
    node_id: "MDQ6VXNlcjgzOTc4MzAx",
    avatar_url: "https://avatars.githubusercontent.com/u/83978301?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/Shahouuudd",
    html_url: "https://github.com/Shahouuudd",
    followers_url: "https://api.github.com/users/Shahouuudd/followers",
    following_url:
      "https://api.github.com/users/Shahouuudd/following{/other_user}",
    gists_url: "https://api.github.com/users/Shahouuudd/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/Shahouuudd/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/Shahouuudd/subscriptions",
    organizations_url: "https://api.github.com/users/Shahouuudd/orgs",
    repos_url: "https://api.github.com/users/Shahouuudd/repos",
    events_url: "https://api.github.com/users/Shahouuudd/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/Shahouuudd/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bsef19a524",
    id: 72218144,
    node_id: "MDQ6VXNlcjcyMjE4MTQ0",
    avatar_url: "https://avatars.githubusercontent.com/u/72218144?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bsef19a524",
    html_url: "https://github.com/bsef19a524",
    followers_url: "https://api.github.com/users/bsef19a524/followers",
    following_url:
      "https://api.github.com/users/bsef19a524/following{/other_user}",
    gists_url: "https://api.github.com/users/bsef19a524/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bsef19a524/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bsef19a524/subscriptions",
    organizations_url: "https://api.github.com/users/bsef19a524/orgs",
    repos_url: "https://api.github.com/users/bsef19a524/repos",
    events_url: "https://api.github.com/users/bsef19a524/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bsef19a524/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "AftabJaved555",
    id: 83979877,
    node_id: "MDQ6VXNlcjgzOTc5ODc3",
    avatar_url: "https://avatars.githubusercontent.com/u/83979877?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/AftabJaved555",
    html_url: "https://github.com/AftabJaved555",
    followers_url: "https://api.github.com/users/AftabJaved555/followers",
    following_url:
      "https://api.github.com/users/AftabJaved555/following{/other_user}",
    gists_url: "https://api.github.com/users/AftabJaved555/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/AftabJaved555/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/AftabJaved555/subscriptions",
    organizations_url: "https://api.github.com/users/AftabJaved555/orgs",
    repos_url: "https://api.github.com/users/AftabJaved555/repos",
    events_url: "https://api.github.com/users/AftabJaved555/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/AftabJaved555/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bsef19a510",
    id: 72216212,
    node_id: "MDQ6VXNlcjcyMjE2MjEy",
    avatar_url: "https://avatars.githubusercontent.com/u/72216212?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bsef19a510",
    html_url: "https://github.com/bsef19a510",
    followers_url: "https://api.github.com/users/bsef19a510/followers",
    following_url:
      "https://api.github.com/users/bsef19a510/following{/other_user}",
    gists_url: "https://api.github.com/users/bsef19a510/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bsef19a510/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bsef19a510/subscriptions",
    organizations_url: "https://api.github.com/users/bsef19a510/orgs",
    repos_url: "https://api.github.com/users/bsef19a510/repos",
    events_url: "https://api.github.com/users/bsef19a510/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bsef19a510/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "UzairAsadBaig",
    id: 66635170,
    node_id: "MDQ6VXNlcjY2NjM1MTcw",
    avatar_url: "https://avatars.githubusercontent.com/u/66635170?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/UzairAsadBaig",
    html_url: "https://github.com/UzairAsadBaig",
    followers_url: "https://api.github.com/users/UzairAsadBaig/followers",
    following_url:
      "https://api.github.com/users/UzairAsadBaig/following{/other_user}",
    gists_url: "https://api.github.com/users/UzairAsadBaig/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/UzairAsadBaig/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/UzairAsadBaig/subscriptions",
    organizations_url: "https://api.github.com/users/UzairAsadBaig/orgs",
    repos_url: "https://api.github.com/users/UzairAsadBaig/repos",
    events_url: "https://api.github.com/users/UzairAsadBaig/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/UzairAsadBaig/received_events",
    type: "User",
    site_admin: false,
  },
  {
    login: "bsef19a512",
    id: 72211935,
    node_id: "MDQ6VXNlcjcyMjExOTM1",
    avatar_url: "https://avatars.githubusercontent.com/u/72211935?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bsef19a512",
    html_url: "https://github.com/bsef19a512",
    followers_url: "https://api.github.com/users/bsef19a512/followers",
    following_url:
      "https://api.github.com/users/bsef19a512/following{/other_user}",
    gists_url: "https://api.github.com/users/bsef19a512/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bsef19a512/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bsef19a512/subscriptions",
    organizations_url: "https://api.github.com/users/bsef19a512/orgs",
    repos_url: "https://api.github.com/users/bsef19a512/repos",
    events_url: "https://api.github.com/users/bsef19a512/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bsef19a512/received_events",
    type: "User",
    site_admin: false,
  },
];
